version: '2'
services:
  dns:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  node1:
    environment:
      - NAME=node1
      - HOST=0.0.0.0
      - PEERS=http://node2:8000/graphql
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    volumes:
      - ./:/naivecoin
    links:
      - explorer1
  node2:
    environment:
      - HOST=0.0.0.0
      - NAME=node2
      - PEERS=http://node3:8000/graphql
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8002:8000'
    volumes:
      - ./:/naivecoin
    links:
      - explorer2
    depends_on:
      - node3
  node3:
    environment:
      - HOST=0.0.0.0
      - NAME=node3
      - PEERS=http://node1:8000/graphql
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8003:8000'
    volumes:
      - ./:/naivecoin
    links:
      - explorer3
    depends_on:
      - node1
  explorer1:
    image: naivecoin-explorer
    environment:
      - REACT_APP_GRAPHQL_SERVER=node1
    ports:
      - '3001:3000'
    volumes:
      - ../naivecoin-explorer:/usr/src/naivecoin-explorer
  explorer2:
    image: naivecoin-explorer
    environment:
      - REACT_APP_GRAPHQL_SERVER=node2
    ports:
      - '3002:3000'
    volumes:
      - ../naivecoin-explorer:/usr/src/naivecoin-explorer
  explorer3:
    image: naivecoin-explorer
    environment:
      - REACT_APP_GRAPHQL_SERVER=node3
    volumes:
      - '../naivecoin-explorer/:/usr/src/naivecoin-explorer'
    ports:
      - '3003:3000'
